apiVersion: apps/v1
kind: Deployment
metadata:
  name: pdf-generator
  namespace: multicloud-dr
  labels:
    app: pdf-generator
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pdf-generator
  template:
    metadata:
      labels:
        app: pdf-generator
        version: v1
    spec:
      nodeSelector:
        workload: microservices
      containers:
      - name: pdf-generator
        image: <ACR_NAME>.azurecr.io/pdf-generator:latest  # Replace <ACR_NAME>
        imagePullPolicy: Always
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        env:
        - name: PORT
          value: "8081"
        - name: AZURE_REGION
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: AZURE_REGION
        - name: COSMOSDB_CONNECTION_STRING
          valueFrom:
            secretKeyRef:
              name: azure-config
              key: COSMOSDB_CONNECTION_STRING
        - name: COSMOSDB_DATABASE
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: COSMOSDB_DATABASE
        - name: STORAGE_CONNECTION_STRING
          valueFrom:
            secretKeyRef:
              name: azure-config
              key: STORAGE_CONNECTION_STRING
        - name: STORAGE_CONTAINER
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: STORAGE_CONTAINER
        - name: APPINSIGHTS_INSTRUMENTATION_KEY
          valueFrom:
            secretKeyRef:
              name: azure-config
              key: APPINSIGHTS_INSTRUMENTATION_KEY
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8081
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8081
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: pdf-generator
  namespace: multicloud-dr
  labels:
    app: pdf-generator
spec:
  type: ClusterIP
  ports:
  - port: 8081
    targetPort: 8081
    protocol: TCP
    name: http
  selector:
    app: pdf-generator
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: pdf-generator-hpa
  namespace: multicloud-dr
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: pdf-generator
  minReplicas: 2
  maxReplicas: 6
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
